### PR TITLE
pushing backend

### PR DESCRIPTION
**Pull request by jawndiego**
dreamweaver -> assembly-press/backend

### CODE REVIEW

**Comment by jawndiego** [comment]
@salieflewis @0xTranqui pls review

**Comment by 0xTranqui** [comment]
Screenshot 2023-07-31 at 11 02 31 PM

@jawndiego im merging this but can u plz just adjust some of the font size on the readme its looking a lil crazy

**Review by 0xTranqui — COMMENTED** [review]
all systems go

**Comment by 0xTranqui** [comment]
@jawndiego oh also using the word "owner" to describe whos private key is funding the arweave stuff is confusing. maybe we call this privateKeyForBundlr or something? idk. im aware that "owner" is how its classified in the bundlr api

**Pull request merged**
