### PR TITLE
Salief/update to protocol changes

### PR DESCRIPTION
**Pull request by salieflewis**
cc: @jawndiego @0xTranqui

### CODE REVIEW

**Comment by 0xTranqui** [comment]
Screenshot 2023-08-21 at 12 34 36 PM

can we confirm that well be able to access the data thats getting passed into the setup function (other function as well) which is what wed need to be able to know what the logic and renderer contracts for a given Press??

Im optimistic well be able to, since that input data is returned on [etherscan](https://goerli-optimism.etherscan.io/tx/0x0c9b86c2f3fd93a5ba8aded1e39dadc7366eab7c1a87b659790e31fba38ba742) (factory init) , but not 100% sure we can get that from the viem event logging

**Comment by salieflewis** [comment]
> Screenshot 2023-08-21 at 12 34 36 PM
> can we confirm that well be able to access the data thats getting passed into the setup function (other function as well) which is what wed need to be able to know what the logic and renderer contracts for a given Press??
> 
> Im optimistic well be able to, since that input data is returned on [etherscan](https://goerli-optimism.etherscan.io/tx/0x0c9b86c2f3fd93a5ba8aded1e39dadc7366eab7c1a87b659790e31fba38ba742) (factory init) , but not 100% sure we can get that from the viem event logging

Yeah, we'll need to confirm this. On a side note, are there individual events emitted when the Logic and Renderer contracts are updated? Or is that just included in `PressDataUpdated`

**Comment by 0xTranqui** [comment]
logic and renderer updates will be recorded in logic + renderer routers that well set up. they wont be in the router tho bc its too sspeciic for that level imo

**Comment by salieflewis** [comment]
> logic and renderer updates will be recorded in logic + renderer routers that well set up. they wont be in the router tho bc its too sspeciic for that level imo
> 
> to be clear, logic + renderer update events will not come from the router. well need to be running extra indexing on the logic and renderers we setup. and also well need to come up with a solution for picking up "Collected" events which are emitted at the Press level. maybe Goldsky just for that?

Hmm okay, good to know. We could probably lump the Router and Logic events in with the general indexing, but for indexing individual Press contracts yeah we might need to turn to something that supports factories.

**Pull request merged**
